version: '3.4'

services:
  webapi:
    container_name: LetsTalk.WebApi
    image: ${DOCKER_REGISTRY-}letstalk_webapi
    build:
      context: .
      dockerfile: LetsTalk.WebApi/Dockerfile
    depends_on:
      - cache
      - database
  cache:
    container_name: RedisCache
    image: redis
  database:
    container_name: MongoDb
    image: mongo
  dbadmin:
    container_name: MongoExpress
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: database
    depends_on:
      - database
