version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}letstalk_webapi
    build:
      context: .
      dockerfile: LetsTalk.WebApi/Dockerfile
    depends_on:
      - cache
      - database
  cache:
    container_name: cache
    image: redis
  database:
    container_name: database
    image: mongo
  database_admin:
    container_name: database_admin
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: database
    depends_on:
      - database
